export default[
    'India',
    'Pakistan',
    'sri lanks',
    'china',
    'USA',
    'UK',
    'UAE',
    'Australia',
    'Malaysia',
    'Singapore',
    'Indonesia',
    'Japan',
    'South Korea',
    'Myanmar',
    'Isral',
    'Palestine',
    'Egypt',
    'Saudi Arabia',
    'Iran',
    'Iraq',
    'Bahrain',
    'Qatar',
    'South Africa',
    'Germany',
    'Switzerland',
    'Russia',
    'Ukrain',
    'France',
    'Poland',
    'Spain',
    'Italy',
    'Netherlands',
    'Norway',
    'Sweden',
    'Ireland',
    'Finland',
    'Romania',
    'Greece',
    'Turkey',
    'Portugal',
    'Denmark',
    'Croatia',
    'Serbia',
    'Hungary',
    'Belarus',
    'Brazil',
    'Argentina',
    'Canada',
    'Mexico',
    'Equador',
    'Venezuela',
];